import { ArrowUpRight, BriefcaseBusiness, CheckCircle2, ChevronRight, Clock3, FileText, Flame, MoreHorizontal, Play, Sparkles, Target, TrendingUp, Trophy, Zap } from 'lucide-react'

const actions = ['Tailor your resume for the Product Designer role at Linear', 'Complete your Figma skill assessment', 'Practice your upcoming interview with Stripe']
const activity = [
  { icon: FileText, color: 'purple', title: 'Resume updated', detail: 'Added 2 quantified achievements', time: '2h ago' },
  { icon: BriefcaseBusiness, color: 'blue', title: 'Application moved to Interview', detail: 'Product Designer · Stripe', time: 'Yesterday' },
  { icon: Trophy, color: 'orange', title: 'Milestone completed', detail: 'Build your design portfolio', time: '2 days ago' },
]

export default function DashboardPage() {
  return <div className="content"><div className="page-heading"><div><p className="eyebrow">Monday, September 29, 2025</p><h1>Good morning, Jordan <span>✦</span></h1><p className="muted">You’re making great progress. Here’s your career snapshot.</p></div><button className="primary"><Sparkles size={16}/> Ask CareerOS</button></div>
    <section className="hero-grid"><div className="health-card card"><div className="card-title"><div><p className="eyebrow">Career health</p><h2>Looking strong</h2></div><span className="trend"><TrendingUp size={14}/> +8%</span></div><div className="health-body"><div className="score-ring"><div><strong>78</strong><small>/ 100</small></div></div><div className="health-list"><div><span className="dot green"/> Resume quality <b>92%</b></div><div><span className="dot blue"/> Application activity <b>64%</b></div><div><span className="dot purple"/> Skill progress <b>76%</b></div><div><span className="dot orange"/> Interview readiness <b>81%</b></div></div></div><button className="text-button">View detailed report <ArrowUpRight size={15}/></button></div><div className="streak-card card"><div className="card-title"><div><p className="eyebrow">Your momentum</p><h2>7 day streak <Flame size={19} fill="currentColor" className="flame"/></h2></div><MoreHorizontal size={18} className="muted"/></div><div className="streak-days">{['M','T','W','T','F','S','S'].map((day, i) => <div key={i} className={i < 5 ? 'day done' : 'day'}><span>{day}</span>{i < 5 ? <CheckCircle2 size={19}/> : <span className="empty-day"/>}</div>)}</div><div className="streak-footer"><div><strong>12</strong><span>tasks completed</span></div><div><strong>4.2h</strong><span>career time</span></div><div><strong>+24</strong><span>XP earned</span></div></div></div></section>
    <section className="stats-grid"><Stat icon={BriefcaseBusiness} color="blue" label="Applications this week" value="8" note="+3 from last week"/><Stat icon={Clock3} color="orange" label="Upcoming interviews" value="2" note="Next: Tomorrow, 10:00 AM"/><Stat icon={Target} color="purple" label="Skills in progress" value="6" note="2 milestones this week"/><Stat icon={Zap} color="green" label="AI credits remaining" value="842" note="Resets in 18 days"/></section>
    <section className="lower-grid"><div className="card next-actions"><div className="section-heading"><div><h2>Recommended next actions</h2><p className="muted">Small steps that move you forward</p></div><button className="ghost">View all <ChevronRight size={15}/></button></div>{actions.map((action, i) => <div className="action-row" key={action}><span className={`action-number n${i}`}>{i + 1}</span><div><strong>{action}</strong><small>{i === 0 ? 'High impact · 15 min' : i === 1 ? 'Skill growth · 10 min' : 'Interview prep · 20 min'}</small></div><button className="action-play"><Play size={13} fill="currentColor"/></button></div>)}</div><div className="card activity-card"><div className="section-heading"><div><h2>Recent activity</h2><p className="muted">Your latest wins</p></div><button className="ghost">See all <ChevronRight size={15}/></button></div>{activity.map(({ icon: Icon, color, title, detail, time }) => <div className="activity-row" key={title}><span className={`activity-icon ${color}`}><Icon size={16}/></span><div><strong>{title}</strong><small>{detail}</small></div><time>{time}</time></div>)}</div></section>
  </div>
}
function Stat({ icon: Icon, color, label, value, note }: { icon: typeof BriefcaseBusiness, color: string, label: string, value: string, note: string }) { return <div className="stat card"><span className={`stat-icon ${color}`}><Icon size={18}/></span><div><span className="stat-label">{label}</span><strong>{value}</strong><small>{note}</small></div></div> }
